### ISSUE TITLE
(optional) Convert Repository to Typescript (or create a new "side" Fork for it)?

### ISSUE THREAD

**Issue by bcha92** [tech-tankorg/dictionary-app#1]
More of a conversation starter for anyone trying out how to start or respond to issues in general.

It's another way to contribute to a public repo! 😄 🎉

**Comment by nonsoo** [comment]
I can actually add issue templates to this project! It may make it easier to get started with creating issues for the project 😄

**Comment by nonsoo** [comment]
Done!!
